# Generated by Django 4.1.6 on 2023-02-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=30)),
                ('UF', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('UF', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('produtos', models.ManyToManyField(blank=True, to='main.produto')),
            ],
        ),
    ]
